apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
     mylable: test
spec:
   containers:
     - name: test
       image: methuna90/dockerhub:php-jenkins

---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
   selector:
       mylable: test
   ports:
        - name: http
          port: 80
          nodePort: 30080
   type:  NodePort
